# Generated by Django 4.1.7 on 2026-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Прізвище"),
        ),
    ]
