# Generated by Django 4.2.30 on 2026-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_player_first_name_alter_player_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Прізвище"),
        ),
    ]
