# Generated by Django 4.2.30 on 2026-05-31 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_player_first_name_alter_player_last_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerrating",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="playerrating",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator("0"),
                    django.core.validators.MaxValueValidator("10"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="playerrating",
            constraint=models.UniqueConstraint(
                fields=("from_player", "to_player"), name="unique_player_rating"
            ),
        ),
    ]
