# Generated by Django 4.2.30 on 2026-06-02 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_game_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="owner",
        ),
        migrations.AddField(
            model_name="game",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="organizer",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="players_num",
            field=models.IntegerField(
                default=2, validators=[django.core.validators.MinValueValidator("2")]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="teams_num",
            field=models.IntegerField(
                default=2, validators=[django.core.validators.MinValueValidator("2")]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="place"
            ),
        ),
    ]
