# Generated by Django 4.2.30 on 2026-06-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_game_owner_game_city_game_organizer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="players_num",
            new_name="max_players",
        ),
    ]
