# Generated by Django 4.2.30 on 2026-06-02 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rename_players_num_game_max_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="teams_num",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="playerrating",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
