# Generated by Django 4.2.30 on 2026-06-02 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_game_max_players_alter_game_teams_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
