# Generated by Django 4.2.30 on 2026-06-03 09:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_game_city_alter_game_organizer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to=main.models.player_avatar_path,
                verbose_name="Аватар",
            ),
        ),
    ]
