# Generated by Django 4.2.30 on 2026-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_player_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="additional_info",
            field=models.TextField(blank=True, verbose_name="Додаткова інформація"),
        ),
        migrations.AlterField(
            model_name="game",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Місто"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Місце"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Початок"),
        ),
    ]
