# Generated by Django 4.2.30 on 2026-06-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_game_additional_info_alter_game_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="additional_info",
            new_name="note",
        ),
    ]
