# Generated by Django 4.2.30 on 2026-06-03 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_additional_info_game_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2)],
                verbose_name="Максимум гравців",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games", to=settings.AUTH_USER_MODEL, verbose_name="Гравці"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="teams_num",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2)],
                verbose_name="Кількість команд",
            ),
        ),
    ]
