# Generated by Django 4.2.30 on 2026-06-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_game_max_players_alter_game_players_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerrating",
            name="to_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
