# Generated by Django 4.2.30 on 2026-06-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_playerrating_to_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="Логін"),
        ),
    ]
