# Generated by Django 4.2.30 on 2026-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_player_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Прізвище"
            ),
        ),
    ]
