# Generated by Django 4.2.30 on 2026-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_player_first_name_alter_player_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Ім'я"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Прізвище"
            ),
            preserve_default=False,
        ),
    ]
