# Generated by Django 4.2.30 on 2026-06-04 15:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_player_first_name_alter_player_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default-avatar.png",
                upload_to=main.models.player_avatar_path,
                verbose_name="Аватар",
            ),
        ),
    ]
