# Generated by Django 4.2.30 on 2026-06-04 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_player_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гравці",
            ),
        ),
    ]
