# Generated by Django 6.0.6 on 2026-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_game_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="about_me",
            field=models.TextField(blank=True, verbose_name="Про себе"),
        ),
    ]
