# Generated by Django 6.0.6 on 2026-06-10 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_player_about_me"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="starts_at",
        ),
        migrations.AddField(
            model_name="game",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Час"
            ),
            preserve_default=False,
        ),
    ]
