# Generated by Django 6.0.6 on 2026-06-10 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_game_starts_at_game_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="game",
            name="start_time",
        ),
        migrations.AddField(
            model_name="game",
            name="starts_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата і час"
            ),
            preserve_default=False,
        ),
    ]
